# SPDX-FileCopyrightText: 2026 Dominik Wombacher <dominik@wombacher.cc>
#
# SPDX-License-Identifier: Apache-2.0

collections:
  - name: https://github.com/ansible-collections/ansible.posix.git
    type: git
    version: 2.1.0
  - name: https://github.com/k3s-io/k3s-ansible.git
    type: git
  - name: https://github.com/dev-sec/ansible-collection-hardening.git
    type: git
    version: 10.5.0
