# SPDX-FileCopyrightText: 2026 Dominik Wombacher <dominik@wombacher.cc>
#
# SPDX-License-Identifier: Apache-2.0

---
- name: Entrypoint to run all playbooks
  hosts: all
  become: true
  gather_facts: true

- name: Deploy k3s cluster
  ansible.builtin.import_playbook: k3s.orchestration.site
...
